from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
import os

CERTS_DIR = "certs"

def generate_certificate(drive, result, start_time, end_time):
    # build filename as YYMMDD_serial.pdf
    date_str = datetime.now().strftime("%y%m%d")
    serial = drive.get("serial", "unknown").replace(" ", "_")
    filename = f"{date_str}_{serial}.pdf"
    filepath = os.path.join(CERTS_DIR, filename)

    os.makedirs(CERTS_DIR, exist_ok=True)

    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter

    # title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, height - 80, "Certificate of Data Destruction")

    # drive details section
    c.setFont("Helvetica", 12)
    y = height - 150
    line_height = 22

    fields = [
        ("Drive Model", drive.get("model", "")),
        ("Serial Number", drive.get("serial", "")),
        ("Capacity", drive.get("size", "")),
        ("Drive Type", drive.get("type", "")),
        ("Wipe Method", get_method_name(drive.get("type", ""))),
        ("Start Time", start_time),
        ("End Time", end_time),
    ]

    for label, value in fields:
        c.drawString(80, y, f"{label}:")
        c.drawString(250, y, str(value))
        y -= line_height

    # result, shown prominently
    y -= 20
    c.setFont("Helvetica-Bold", 16)
    color = (0, 0.5, 0) if result == "PASS" else (0.8, 0, 0)
    c.setFillColorRGB(*color)
    c.drawString(80, y, f"Result: {result}")
    c.setFillColorRGB(0, 0, 0)  # reset color

    # footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(80, 50, f"Generated by WipeStation on {datetime.now().isoformat()}")

    c.save()
    return filepath

def get_method_name(drive_type):
    # maps drive type to the wipe tool/standard used
    methods = {
        "HDD": "nwipe (multi-pass overwrite)",
        "SSD": "hdparm ATA Secure Erase",
        "NVMe": "nvme-cli sanitize",
    }
    return methods.get(drive_type, "Unknown")

if __name__ == "__main__":
    # quick test with fake data
    test_drive = {
        "name": "sdb",
        "model": "WDC WD1003FBYX",
        "serial": "WD-TEST1234",
        "size": "1.0T",
        "type": "HDD",
    }
    path = generate_certificate(test_drive, "PASS", "2026-06-21T10:00:00", "2026-06-21T11:30:00")
    print(f"certificate saved to {path}")